apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-namespace
  labels:
    app: nginx
    resource: service
  annotations:
    description: "LoadBalancer for NGINX"
spec:
  selector:
    app: nginx
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
